name: mlss
# Conda environment for the Machine Learning for Social Sciences course.
# Includes packages used across Jupyter notebooks in the book/ directory
# as well as common machine learning libraries.
channels:
  - conda-forge
  - defaults
dependencies:
  # Core scientific computing
  - python=3.10
  - numpy=1.24.*
  - pandas=2.0.*
  - scipy=1.10.*
  
  # Machine learning
  - scikit-learn=1.3.*
  - statsmodels=0.14.*
  
  # Deep learning
  - pytorch=2.0.*
  
  # Visualization
  - matplotlib=3.7.*
  - bokeh=3.*
  - graphviz
  - dot2tex

  # Jupyter and development
  - jupyter=1.0.*
  - jupyterlab=4.0.*
  - ipywidgets=8.0.*
  - nb_conda_kernels=2.3.*
  - ipython=8.*
  
  # Data manipulation and analysis
  - openpyxl=3.1.*  # Excel support
  - pip
  - pip:
      - google-generativeai
      - huggingface_hub
      - transformers
      - jupyterlab_widgets>=3
      - statwrap
