name: build-and-deploy
on: [push]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1  Checkout repo
      - uses: actions/checkout@v4

      # 2  Python & Node toolchain
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build deps
        run: |
          pip install -r book/requirements.txt
          npm install -g staticrypt

      # 3  Build the book
      - name: Build Jupyter-Book
        run: jupyter-book build book

      # 4  Encrypt every HTML page
      - name: Encrypt HTML
        env:
          BOOK_PW: ${{ secrets.BOOK_PW }}
        run: |
          # Create a temporary directory for encrypted files
          mkdir -p /tmp/encrypted_output
          
          # Encrypt all HTML files recursively with session persistence
          staticrypt book/_build/html -r \
            -p "$BOOK_PW" --short \
            --remember 120 \
            -d /tmp/encrypted_output
          
          # Replace original files with encrypted ones
          rm -rf book/_build/html
          mv /tmp/encrypted_output/html book/_build
          
          # Create .nojekyll file to disable Jekyll processing
          touch book/_build/html/.nojekyll

      # 5  Publish to the gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: book/_build/html
